feat/creation of the call to action section, as instructed by Figma Designer
w3b3d3v/web3task-lp pull request #28
Opened 2024-02-28 14:11 UTC by Hardsys-Andre

I created this section according to Figma, using TailwindCSS, making the component responsive to various screen sizes, including mobile.
Below is an illustrative image of the component:
![image](https://github.com/w3b3d3v/web3task-lp/assets/92451764/1ac8b4ee-136c-4f07-a38b-60f93fe31eff)

2024-03-02 20:52 UTC, heronlancellot requested changes
Hey yo @Hardsys-Andre ! GJ !

2024-03-02 20:52 UTC, heronlancellot commented on src/components/02-molecules/CardCallToAction.tsx
hey yo @Hardsys-Andre ! GJ ! Some fixes to merge it ! 
-  [ ] Check the fonts on mobile
-  [ ] remove the Ethereum Icon & bitcoin Icon ( mobile ) like figma ;)
-  [ ] Adjust the spacing between the button and text 👍

2024-03-04 12:56 UTC, Hardsys-Andre commented
@heronlancellot, The requested adjustments have been made for the mobile version, I thought the 50px size looked better in the mobile version with a screen size of 320px.

![image](https://github.com/w3b3d3v/web3task-lp/assets/92451764/ee9c9d78-f3ec-449d-8401-e4bd2db46d8c)

2024-03-04 20:54 UTC, heronlancellot approved these changes
hey yo @Hardsys-Andre ! 
GJ ! 🚀 🚀

2024-03-04 20:55 UTC, merged