Feat/Footer Section #issue21
w3b3d3v/web3task-lp pull request #29
Opened 2024-03-04 13:20 UTC by Hardsys-Andre

The Footer Section was created, following Figma Designer's instructions and responsiveness was also configured for adjustment in the Mobile version, following Figma Designer's guidance.

Below is an illustrative image of the component:
![image](https://github.com/w3b3d3v/web3task-lp/assets/92451764/d9580fb7-27f0-4844-99bb-7bf62ce993e7)

and version mobile:
![image](https://github.com/w3b3d3v/web3task-lp/assets/92451764/9cef061d-0895-43e6-b396-0ab4141b3dc4)

2024-03-04 21:29 UTC, heronlancellot requested changes
hey yo @Hardsys-Andre ! GJ !
I made some comments * 
Nice coding ! :)

2024-03-04 21:29 UTC, heronlancellot commented on src/app/page.tsx
> +import { TheFooterSection } from "@/components/04-templates/TheFooterSection";
hey yo @Hardsys-Andre ! 
Maybe we can import TheFooterSection like the others
``@/components/04-templates"``

2024-03-04 21:29 UTC, heronlancellot commented on src/app/public/the-footer/instagran-icon.png
hey yo! just change the name to Camel case
``InstagramIcon`` 
in ``public/`` for example, we are using camelCase in files

2024-03-04 21:29 UTC, heronlancellot commented on src/app/public/the-footer/twiter-icon.png
same in that one 👍

2024-03-04 21:29 UTC, heronlancellot commented on src/app/public/the-footer/vector.svg
maybe we can change the name ``vector`` to another name more understandable what it is about without clicking on it 🤔 maybe ArrowUp? or another name... @Hardsys-Andre

2024-03-04 21:29 UTC, heronlancellot commented on src/components/01-atoms/CardTheFooterLayout.tsx
hey yo @Hardsys-Andre ! Beautiful component 💯

2024-03-04 21:29 UTC, heronlancellot commented on src/components/02-molecules/CardTheFooter.tsx
hey yo ! 
- [ ] Just check on the tablet device why it is not aligned
![image](https://github.com/w3b3d3v/web3task-lp/assets/57544272/5e0db6e7-7c82-4531-a31c-2349b14ffeab)
&  Remove unused comment // CardsTheFooter

2024-03-04 21:29 UTC, heronlancellot commented on src/components/03-organisms/TheFooter.tsx
- [ ] Remove unused code
- [ ] Adjust the imports to ``@/components/``
- [ ] update the name of the imports when updating the pngs ( ``InstagramIcon`` etc )
Also, the use of ``absolute`` in those divs doesn't look necessary.. Try to remove it and change to ``flex`` or even ``grid``
Also, check why the icon it's not aligned
![image](https://github.com/w3b3d3v/web3task-lp/assets/57544272/9b3fc786-d566-436b-a4f6-825a52e75e5d)

2024-03-07 14:17 UTC, Hardsys-Andre commented
hello @heronlancellot, PR updated as per requests

2024-03-08 02:11 UTC, heronlancellot approved these changes
hey yo @Hardsys-Andre ! LG 🪨

2024-03-08 02:11 UTC, merged