feat/insertion of transition effects in some components.
w3b3d3v/web3task-lp pull request #38
Opened 2024-05-10 00:29 UTC by Hardsys-Andre

I inserted some transition effects on the Landing Page in order to make the page more attractive.

2024-05-10 16:34 UTC, Hardsys-Andre commented
Hello @Guboehm, Once the adjustments to the effects and the dApp button in the footer were completed, the logo in the header was also changed.

2024-05-11 00:13 UTC, Guboehm requested changes

2024-05-11 00:13 UTC, Guboehm commented on src/components/04-templates/HeroSection.tsx
> +			id=""
Is this id really empty?

2024-05-11 00:13 UTC, Guboehm commented on src/components/01-atoms/ui/randomMovingImage.tsx
> +					animation: "randomMove2 25s linear infinite", // 10 segundos de duração, loop infinito
remove all comments

2024-05-11 01:13 UTC, Hardsys-Andre commented
Hello @Guboehm, removing comments in the randomMovingImage file code and inserting a link in the logo to return to the top of the page.

2024-05-17 01:21 UTC, Guboehm approved these changes

2024-05-17 01:22 UTC, merged